/** Rotating motivational quotes — picked by day-of-year so it's stable per day. */
export const QUOTES: { text: string; author: string }[] = [
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "The only way to prove you're a good sport is to lose.", author: "Ernie Banks" },
  { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
  { text: "Everybody has talent, but ability takes hard work.", author: "Michael Jordan" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "The difference between the impossible and the possible lies in determination.", author: "Tommy Lasorda" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Pressure is a privilege.", author: "Billie Jean King" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Talent wins games, but teamwork wins championships.", author: "Michael Jordan" },
  { text: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
  { text: "Success is where preparation and opportunity meet.", author: "Bobby Unser" },
  { text: "Once you learn to quit, it becomes a habit.", author: "Vince Lombardi" },
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
  { text: "Excellence is not a singular act but a habit. You are what you do repeatedly.", author: "Aristotle" },
  { text: "If you fail to prepare, you're prepared to fail.", author: "Mark Spitz" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { text: "The will to win is nothing without the will to prepare.", author: "Juma Ikangaa" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Persistence can change failure into extraordinary achievement.", author: "Matt Biondi" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "Little things make big things happen.", author: "John Wooden" },
  { text: "Wisdom is always an overmatch for strength.", author: "Phil Jackson" },
  { text: "The more difficult the victory, the greater the happiness in winning.", author: "Pelé" },
  { text: "Success isn't owned. It's leased, and rent is due every day.", author: "J.J. Watt" },
  { text: "Skill is only developed by hours and hours of work.", author: "Usain Bolt" },
  { text: "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you.", author: "Derek Jeter" },
  { text: "I've failed over and over again in my life, and that is why I succeed.", author: "Michael Jordan" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice" },
  { text: "Obstacles don't have to stop you. Figure out how to climb it.", author: "Michael Jordan" },
  { text: "Gold medals aren't really made of gold. They're made of sweat, determination, and guts.", author: "Dan Gable" },
  { text: "The vision of a champion is bent over, drenched in sweat, when no one else is watching.", author: "Mia Hamm" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps" },
  { text: "Confidence comes from discipline and training.", author: "Robert Kiyosaki" },
  { text: "Amateurs practice until they get it right. Pros practice until they can't get it wrong.", author: "Unknown" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John Maxwell" },
  { text: "What you lack in talent can be made up with desire, hustle, and giving 110% all the time.", author: "Don Zimmer" },
  { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant" },
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", author: "Kobe Bryant" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant" },
  { text: "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The score takes care of itself when you take care of the effort.", author: "Bill Walsh" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
];

export function quoteOfDay(d = new Date()): { text: string; author: string } {
  const start = new Date(d.getFullYear(), 0, 0);
  const day = Math.floor((d.getTime() - start.getTime()) / 86400000);
  return QUOTES[day % QUOTES.length];
}
